api:
  security:
    token:
      secret: my-secret-key
server:
  port: 8080
spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/finance-control
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      format_sql: true
  sql:
    init:
      platform: postgres